Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\loggers\wandb.py:341: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(
wandb: WARNING Serializing object of type DataFrame that is 929061 bytes
  | Name              | Type     | Params
-----------------------------------------------
0 | feature_extractor | ResNet   | 11.7 M
1 | classifier        | Linear   | 2.0 K
2 | train_accuracy    | Accuracy | 0
3 | train_f1          | F1       | 0
4 | val_accuracy      | Accuracy | 0
5 | val_f1            | F1       | 0
6 | val_fbeta         | FBeta    | 0
7 | test_accuracy     | Accuracy | 0
8 | test_f1           | F1       | 0
9 | test_fbeta        | FBeta    | 0
-----------------------------------------------
2.0 K     Trainable params
11.7 M    Non-trainable params
11.7 M    Total params
23.383    Total estimated model params size (MB)
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(








Epoch 0:  72%|███████▏  | 61/85 [00:18<00:07,  3.35it/s, loss=0.315, v_num=3wpq, Train_loss_step=0.256]


Validating:  69%|██████▉   | 18/26 [00:04<00:01,  4.19it/s]







Epoch 1:  71%|███████   | 60/85 [00:14<00:06,  4.09it/s, loss=0.246, v_num=3wpq, Train_loss_step=0.173, Val_loss=0.282, Acc_val=0.898, Train_loss_epoch=0.466]


Validating:  65%|██████▌   | 17/26 [00:03<00:02,  4.48it/s]








Epoch 2:  78%|███████▊  | 66/85 [00:15<00:04,  4.15it/s, loss=0.251, v_num=3wpq, Train_loss_step=0.256, Val_loss=0.275, Acc_val=0.906, Train_loss_epoch=0.262]


Validating:  92%|█████████▏| 24/26 [00:05<00:00,  4.40it/s]







Epoch 3:  71%|███████   | 60/85 [00:15<00:06,  3.89it/s, loss=0.216, v_num=3wpq, Train_loss_step=0.172, Val_loss=0.269, Acc_val=0.906, Train_loss_epoch=0.243]



Validating:  73%|███████▎  | 19/26 [00:05<00:02,  3.17it/s]










Epoch 4:  71%|███████   | 60/85 [00:19<00:08,  3.10it/s, loss=0.238, v_num=3wpq, Train_loss_step=0.0989, Val_loss=0.257, Acc_val=0.906, Train_loss_epoch=0.236]



Validating:  81%|████████  | 21/26 [00:07<00:01,  3.29it/s]










Epoch 5:  71%|███████   | 60/85 [00:19<00:08,  3.09it/s, loss=0.217, v_num=3wpq, Train_loss_step=0.242, Val_loss=0.255, Acc_val=0.908, Train_loss_epoch=0.229]



Validating:  77%|███████▋  | 20/26 [00:06<00:01,  3.01it/s]
Epoch 5, global step 353: Val_loss reached 0.25686 (best 0.25518), saving model to "C:\Users\rufai\Downloads\assignment-instructions\assignment\best-model\OilPalmRes\-epoch=05--val_loss=0.00.ckpt" as top 5
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
wandb: WARNING Serializing object of type DataFrame that is 929061 bytes
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.





Testing: 100%|██████████| 36/36 [00:09<00:00,  4.53it/s]\Test Accuracy: 0.0000, F1 Score: 0.0000FBeta Score: 0.0000
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'Acc_test': 0.9223090410232544,
 'Test_F1': 0.7914764285087585,
 'Test_FBeta': 0.7914764285087585}
--------------------------------------------------------------------------------
Testing: 100%|██████████| 36/36 [00:09<00:00,  3.63it/s]
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric Accuracy was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric F1 was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric FBeta was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)