




Epoch 0, global step 58: Val_loss reached 0.33385 (best 0.33385), saving model to "C:\Users\rufai\Downloads\assignment-instructions\assignment\best-model\len7\epoch=0-step=58-v1.ckpt" as top 1


Validating:  88%|████████▊ | 23/26 [00:05<00:00,  4.33it/s]




Validating:  85%|████████▍ | 22/26 [00:05<00:00,  4.27it/s]




Validating:  73%|███████▎  | 19/26 [00:04<00:01,  4.05it/s]






Epoch 4, global step 294: Val_loss was not in top 1



Epoch 5, global step 353: Val_loss reached 0.29955 (best 0.29955), saving model to "C:\Users\rufai\Downloads\assignment-instructions\assignment\best-model\len7\epoch=5-step=353-v5.ckpt" as top 1
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
C:\Users\rufai\anaconda3\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, test_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.




Testing:  97%|█████████▋| 35/36 [00:09<00:00,  3.47it/s]\Test Accuracy: 0.0000, F1 Score: 0.0000FBeta Score: 0.0000
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'Acc_test': 0.8723958134651184,
 'Test_F1': 0.4659249186515808,
 'Test_FBeta': 0.4659249186515808}
--------------------------------------------------------------------------------
Testing: 100%|██████████| 36/36 [00:09<00:00,  3.79it/s]
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric Accuracy was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric F1 was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)
C:\Users\rufai\anaconda3\lib\site-packages\torchmetrics\utilities\prints.py:36: UserWarning: The ``compute`` method of metric FBeta was called before the ``update`` method which may lead to errors, as metric states have not yet been updated.
  warnings.warn(*args, **kwargs)